spring.application.name=simple-directory-api
server.port=8080

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=1s

app.directoryRateLimiter.defaultLimitWithinWindow=5
app.directoryRateLimiter.accumulationWindowSeconds=60
